### PR TITLE
Fix Issue 70

### PR DESCRIPTION
**Pull request by sauzher**
Drop the use of  `JazkartaShopCalendarDatePickerBox` in favor of modern Plone Mockup pattern `pat-pickadate`

### CODE REVIEW

**Review by alecpm — APPROVED** [review]
LGTM

**Comment by alecpm** [comment]
This work was merged with PR #77

**Comment by witekdev** [comment]
in /@@jazkarta-shop-orders

What I found is that after one selects the date range and hits update selection, when page reloads, the selected dates are not remembered anymore. Instead the datepickers are reset.

Also this might be client specific issue, but since this is control panel (ie not themed) what I see is we could potentially add some style fixes in this package? See "September" and "2022" being cut off

Untitled-3

@alecpm @sauzher did you notice this ? ^

**Comment by alecpm** [comment]
@witekdev Neither of those seem to be a problem on NCI: https://test.ncascades.org/jazkarta-shop-orders?Start-Date=2019-03-14&_submit=2019-03-14&End-Date=2020-03-18&_submit=2020-03-18&submitted=Update+Selection&_authenticator=eae4274e2e81d7ac7365aaf36c9de41ba0c7838f

**Comment by alecpm** [comment]
I think we can work under the assumption that the default styling of the default date picker is acceptable and sites where it looks strange need to tweak it in their theme as a result of non-default font configurations. Not sure why the date wouldn't be retained on some sites though, that might be worth looking into.

**Comment by witekdev** [comment]
@alecpm well that is bizarre, it is now working for me on my local test instance as well. (date selection being retained)
sure for the dropdown sizes, we can defer that to local site css to tweak if necessary

**Pull request closed without merging**
